### ISSUE TITLE
No support for unix domain sockets.

### ISSUE THREAD

**Issue by jmgurney** [ipfs-shipyard/py-ipfs-http-client#197]
Newer versions of ipfs support API control via a Unix domain socket.  It would be nice if this was supported.

I'd expect:
```
>>> import ipfshttpclient
>>> client = ipfshttpclient.connect('/unix/var/db/ipfs-go/socket/api.sock')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/ipfs/py-ipfs-http-client/ipfshttpclient/client/__init__.py", line 98, in connect
    client = Client(addr, base, chunk_size, session, **defaults)
  File "/tmp/ipfs/py-ipfs-http-client/ipfshttpclient/client/base.py", line 120, in __init__
    self._client = self._clientfactory(addr, base, **defaults)
  File "/tmp/ipfs/py-ipfs-http-client/ipfshttpclient/http.py", line 208, in __init__
    six.raise_from(exceptions.AddressError(addr), None)
  File "<string>", line 3, in raise_from
ipfshttpclient.exceptions.AddressError: Unsupported Multiaddr pattern: /unix/var/db/ipfs-go/socket/api.sock
```
to work instead of throwing an unsupported Multiaddr.

**Comment by ntninja** [comment]
This has been implemented in #233 to be released shortly.
