### ISSUE TITLE
Method Not Allowed for url: http+ip4://127.0.0.1:5001

### ISSUE THREAD

**Issue by hicetnunc2000** [ipfs-shipyard/py-ipfs-http-client#227]
I'd like to report an error that I got. I'm using 
`ipfs version 0.6.0
Python 3.8.2
pip 20.0.2
`

code:
```
import ipfshttpclient
client = ipfshttpclient.connect('/ip4/127.0.0.1/tcp/5001/http')
res = client.add('ipfs-bash.sh')
print(res)
```
error:
```
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.8/site-packages/ipfshttpclient/http.py", line 266, in _do_raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http+ip4://127.0.0.1:5001/api/v0/version?stream-channels=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ipfs.py", line 3, in <module>
    client = ipfshttpclient.connect('/ip4/127.0.0.1/tcp/5001/http')
  File "/home/xxx/.local/lib/python3.8/site-packages/ipfshttpclient/client/__init__.py", line 101, in connect
    version_str = client.version()["Version"]
  File "/home/xxx/.local/lib/python3.8/site-packages/ipfshttpclient/client/base.py", line 15, in wrapper
    result = func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/ipfshttpclient/client/miscellaneous.py", line 204, in version
    return self._client.request('/version', decoder='json', **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/ipfshttpclient/http.py", line 51, in wrapper
    return func(self, *args, **merged)
  File "/home/xxx/.local/lib/python3.8/site-packages/ipfshttpclient/http.py", line 385, in request
    res = self._request(method, url, params, stream, files, headers,
  File "/home/xxx/.local/lib/python3.8/site-packages/ipfshttpclient/http.py", line 307, in _request
    self._do_raise_for_status(res)
  File "/home/xxx/.local/lib/python3.8/site-packages/ipfshttpclient/http.py", line 286, in _do_raise_for_status
    six.raise_from(exceptions.StatusError(error), error)
  File "<string>", line 3, in raise_from
ipfshttpclient.exceptions.StatusError: HTTPError: 405 Client Error: Method Not Allowed for url: http+ip4://127.0.0.1:5001/api/v0/version?stream-channels=true
```

I've managed to publish the very same file with https://pypi.org/project/ipfs-api/, which seems to be deprecated. Would like to know if there are any updates for such.

I've used pip install ipfshttpclient, maybe there's a newer version?

**Comment by hicetnunc2000** [comment]
It seems that by package was not up to date. Fixed it with `pip3 install git+https://github.com/ipfs-shipyard/py-ipfs-http-client.git`

**Comment by ntninja** [comment]
What version of `ipfshttpclient` are you using? It should be 0.6.0 or it won't work.

> I've managed to publish the very same file with https://pypi.org/project/ipfs-api/, which seems to be deprecated. Would like to know if there are any updates for such.

This statements surprised me, turns out there is a “bug/feature/happenstance” in that old code makes adding objects work. :woman_astronaut: 

Anyways, that library will never be updated again unless Amstocker (inactive main developers of this library) decides to push a release.

**Comment by ntninja** [comment]
> It seems that my package was not up to date. Fixed it with `pip3 install git+https://github.com/ipfs-shipyard/py-ipfs-http-client.git`

You shouldn't need to do that (anymore), installing the `0.6.0` [from PyPI](https://pypi.org/project/ipfshttpclient/) should suffice. :wink:
