### ISSUE TITLE
ipfshttpclient.connect() producing an error

### ISSUE THREAD

**Issue by rounin-rp** [ipfs-shipyard/py-ipfs-http-client#247]
when I try ipfshttpclient.connect() it gives me the following error : 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dexer/anaconda3/envs/IPFS/lib/python3.7/site-packages/ipfshttpclient/client/__init__.py", line 119, in connect
    assert_version(client.apply_workarounds()["Version"])
  File "/home/dexer/anaconda3/envs/IPFS/lib/python3.7/site-packages/ipfshttpclient/client/__init__.py", line 69, in assert_version
    raise exceptions.VersionMismatch(version, minimum, maximum)
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '0.7.0' (not in range: 0.4.22 ≤ … < 0.7.0)

**Comment by driemworks** [comment]
I had the same issue. The connection went through succesfully after installing this version: https://pypi.org/project/ipfshttpclient/0.7.0a1/

**Comment by rounin-rp** [comment]
> I had the same issue. The connection went through succesfully after installing this version: https://pypi.org/project/ipfshttpclient/0.7.0a1/

Thanks man. It works. You're a life saver
