### ISSUE TITLE
HTTPError: 405 Client Error: Method Not Allowed

### ISSUE THREAD

**Issue by Nikolaj4o** [ipfs-shipyard/py-ipfs-http-client#303]
connect method throws an exception : 

ipfshttpclient.exceptions.StatusError: HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/version?stream-channels=true

Does anyone have any idea what might be causing this?

**Comment by carsonfarmer** [comment]
I'm seeing the same with latest pip release. Any ideas on the fix here?

**Comment by Footsiefat** [comment]
Same issue here..

**Comment by jsun28** [comment]
same issue

**Comment by SelcukOz05** [comment]
I am facing this issue too.

**Comment by SelcukOz05** [comment]
https://github.com/ipfs-shipyard/py-ipfs-http-client/issues/218#issuecomment-1014803298
This did it for me.

**Comment by marcellodesales** [comment]
# 🔢 Versions

* ⛓️ IPFS: `go-ifps@0.12.1`
* 🐍 Python `3.9`

# 🐞 Bug

* The server can't request as per the documentation

```console
>>> import ipfsApi
>>> api = ipfsApi.Client('localhost', 5001)
>>> api.id()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/ipfsApi/client.py", line 345, in id
    return self._id.request(self._client, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ipfsApi/commands.py", line 18, in request
    return client.request(self.path, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ipfsApi/http.py", line 25, in wrapper
    return f(self, *args, **merged)
  File "/usr/local/lib/python3.9/site-packages/ipfsApi/http.py", line 95, in request
    res.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://localhost:5001/api/v0/id?stream-channels=true&encoding=json
```

# 🎨 IPFS Server new...

* We can't upgrade anything else.
* Could this be a server-side setting? Since it's not allowing the HTTP request, but the browser itself opens all the settings properly

<img width="1036" alt="Screen Shot 2022-04-05 at 8 04 49 PM" src="https://user-images.githubusercontent.com/131457/161887915-19c20579-aa90-4455-9287-4e89a4290638.png">

**Comment by hemangjoshi37a** [comment]
having same problem in #318

**Comment by hemangjoshi37a** [comment]
The error message "HTTPError: 405 Client Error: Method Not Allowed" typically indicates that the server is not allowing the method (such as GET or POST) used in the request. In this case, it seems that the IPFS API server is not allowing the request to the /api/v0/version endpoint.

It's difficult to say exactly what might be causing this issue without more information about your setup, but here are a few things to check:

1. Verify that the IPFS daemon is running and that it is listening on the correct IP address and port (localhost:5001 by default).
2. Make sure that the version of the IPFS daemon you are running is compatible with the version of the IPFS API client you are using.
3. Verify that the IPFS API server is configured to allow the method used in the request. You can do this by checking the IPFS API server's configuration file or by running the ipfs config show command.
4. Check that the the endpoint is not blocked by any firewall or security group on your network.
5. Try to connect to the IPFS API server from the command line using curl or httpie to see if you can reproduce the issue and get more information about what is causing it.

It is also possible that the error is caused by a bug in the IPFS API client library that you are using. In this case, you may want to check the library's documentation and issue tracker to see if there are any known issues or workarounds.

Finally, One of the user in the issue thread mentioned that adding api = ipfsApi.Client('http://0.0.0.0', 5001) instead of api = ipfsApi.Client('localhost', 5001) worked for them. This could be an option to test if you haven't done yet.

**Comment by amias-channer** [comment]
seems like this lib has been abandoned , i switched to ipfshttpclient 8.0 and this works with kubo 0.37.0

**Comment by hemangjoshi37a** [comment]
@amias-channer  please share link

**Comment by amias-channer** [comment]
https://github.com/ipfs-shipyard/py-ipfs-http-client/issues/218#issuecomment-1014803298
