### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by wongasley** [ipfs-shipyard/py-ipfs-http-client#309]
Traceback (most recent call last):
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/http_httpx.py", line 173, in _request
closables, session = self._access_session()
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/http_common.py", line 417, in _access_session
session = self._make_session()
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/http_httpx.py", line 119, in _make_session
connection_pool = httpcore.SyncConnectionPool(
AttributeError: module 'httpcore' has no attribute 'SyncConnectionPool'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/wongasley/Desktop/RBS/Post.py", line 3, in
client = ipfshttpclient.connect()
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/client/init.py", line 119, in connect
assert_version(client.apply_workarounds()["Version"])
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/client/init.py", line 228, in apply_workarounds
version_info = self.version()
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/client/base.py", line 245, in wrapper2
result = func(*args, **kwargs)
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/client/miscellaneous.py", line 204, in version
return self._client.request('/version', decoder='json', **kwargs)
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/http_common.py", line 613, in request
closables, res = self._request(
File "/home/wongasley/.local/lib/python3.8/site-packages/ipfshttpclient/http_httpx.py", line 202, in _request
for closable in closables:
UnboundLocalError: local variable 'closables' referenced before assignment

**Comment by wongasley** [comment]
It was working fine and then suddenly this error shows up
